### ISSUE TITLE
Please remove my email address from the history of this project

### ISSUE THREAD

**Issue by sharpie7** [E3V3A/circuitjs1#4]
I assume this was a mistake as you edited the file very quickly, but my email address is still visible in the file history which I do not appreciate. Please remove it.

This might be useful:
https://help.github.com/en/articles/removing-sensitive-data-from-a-repository

Thanks

**Comment by E3V3A** [comment]
@sharpie7 
I'm sorry but your commit messages and the email you supply with them **are not** considered *sensitive information*. Your email is all over the commit history (and elsewhere on the internet), so I suggest you remove it from there first. That said, I did remove it from from the README out of common courtesy, but I'm not going through the procedure from hell, that you suggested to try to remove something that is not removable.
